### ISSUE TITLE
Digikey PN for 4.7K resistor is wrong

### ISSUE THREAD

**Issue by MustBeArt** [IBM-1620/Cadetwriter#1]
In the adaptation instructions, in the parts list, the DigiKey part number for the 4.7K resistor is the same as the part number for the 10K resistor. It should be CF18JT4K70CT-ND I think.

**Comment by slcasner** [comment]
Thanks for the bug report.  Fixed in 1d15698cf423c813fa3d037a9fa6028c2801185e
