### ISSUE TITLE
Auto paper load doesn't work

### ISSUE THREAD

**Issue by MustBeArt** [IBM-1620/Cadetwriter#2]
The unmodified Wheelwriter 1000 has a semi-automatic paper loading feature. You pull back on the Paper Bail Load Lever and the paper is automatically fed into the machine and advanced to the top margin. This does not happen with the Cadetwriter board installed, even when configured for Standalone Typewriter mode.

Problem confirmed by Dave Babcock.

**Comment by DaveB1620** [comment]
Problem fixed in firmware version 5R5 for all emulations.  The semi-automatic paper loading feature now works with a standard serial interface board and one modified as described in the Cadetwriter building channel (https://cadetwriter.slack.com).  Fix verified by submitter.
